import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Link from "next/link";
import { Sun } from "lucide-react";
import Header from "@/components/header";
import Footer from "@/components/footer";

const sourceSans = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          sourceSans.className,
          "min-h-svh flex flex-col transition-all"
        )}
      >
        <Header />
        <main className="flex-1 px-6 max-w-screen-xl mx-auto w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
